### ISSUE TITLE
大佬怎么不更新了

### ISSUE THREAD

**Issue by xiaoheimaoo** [FZFalzar/FGOData#3]
已经停了块一个月了

**Comment by FZFalzar** [comment]
Server cost is expensive to maintain monthly without donation

**Comment by squaresmile** [comment]
> 已经停了块一个月了

We maintain a fgo game data repo. You can join our discord at https://discord.gg/TKJmuCR

**Comment by FZFalzar** [comment]
Yes, please use atlas academy's data which is well maintained. Unless there is a need for this repo I do not plan to continue running this server
